ALTER TABLE sessions ADD COLUMN permission_mode TEXT NOT NULL DEFAULT '';
ALTER TABLE sessions ADD COLUMN fork_of TEXT NOT NULL DEFAULT '';
ALTER TABLE sessions ADD COLUMN auto_continue INTEGER NOT NULL DEFAULT 0;
